### ISSUE TITLE
[BUG REPORT] - SQL

### ISSUE THREAD

**Issue by kenshixxx** [Maximus7474/mps_vehiclepersist#1]
Hello i have a problem with script, when I put the sql in xampp I get this error : MySQL has replied: Documentation

#1005 - Cannot create table districtsql.vehicles_persist (Errcode: 150 “Foreign key constraint is incorrectly formed”) (Details...)

Can you help me ?

**Comment by Maximus7474** [comment]
Hmmm, you can try running the snippet again and delete [line 12](https://github.com/Maximus7474/mps_vehiclepersist/blob/main/base.sql#L12) from the query.

It's more as a backup to avoid incorrect id getting set to the table.

**Comment by kenshixxx** [comment]
> Hmmm, you can try running the snippet again and delete [line 12](https://github.com/Maximus7474/mps_vehiclepersist/blob/main/base.sql#L12) from the query.
> 
> It's more as a backup to avoid incorrect id getting set to the table.

it say in console : resource 'mps_vehiclepersist' can't run :
1. constraint 'oxmysql' is unknown

**Comment by Maximus7474** [comment]
Can you send a screenshot of the complete error ?

**Comment by Maximus7474** [comment]
> 1. constraint 'oxmysql' is unknown

This has been resolved on the latest release [v1.0.3](https://github.com/Maximus7474/mps_vehiclepersist/releases/tag/v1.0.3)
